import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="border-b">
          <nav className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
            <a href="/" className="font-bold">
              ShipFast SaaS Lite
            </a>
            <div className="flex gap-4 text-sm">
              <a className="underline-offset-4 hover:underline" href="/pricing">
                Pricing
              </a>
              <a className="underline-offset-4 hover:underline" href="/dashboard">
                Dashboard
              </a>
            </div>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}

